FROM monogramm/docker-erpnext:%%VERSION%%-debian-slim

# Build environment variables
ENV DOCKER_TAG=travis \
    DOCKER_VCS_REF=${TRAVIS_COMMIT} \
    DOCKER_BUILD_DATE=${TRAVIS_BUILD_NUMBER}

# Copy the whole repository to app folder for manual install
#COPY --chown=frappe:frappe . "/home/$FRAPPE_USER"/frappe-bench/apps/erpnext_ocr

ARG BUILD_BRANCH
ARG BUILD_URL

RUN set -ex; \
    sudo apt-get update -q; \
    sudo apt-get install -y --no-install-recommends \
        ghostscript \
        imagemagick \
        tesseract-ocr \
        libleptonica-dev \
        iputils-ping \
    ; \
    sudo sed -i \
        -e 's/rights="none" pattern="PDF"/rights="read" pattern="PDF"/g' \
        /etc/ImageMagick*/policy.xml \
    ; \
    sudo mkdir -p "/home/$FRAPPE_USER"/frappe-bench/logs; \
    sudo touch "/home/$FRAPPE_USER"/frappe-bench/logs/bench.log; \
    sudo chmod 777 \
        "/home/$FRAPPE_USER"/frappe-bench/logs \
        "/home/$FRAPPE_USER"/frappe-bench/logs/* \
    ; \
    bench get-app --branch ${BUILD_BRANCH} ${BUILD_URL}
    #echo "Manually installing app for CI (not needed normally)"; \
    #./env/bin/pip install -q -e "apps/erpnext_ocr" --no-cache-dir; \
    #test ! "$FRAPPE_BRANCH" = "v10.x.x" \
    #    && ./env/bin/pip3 install -q -e "apps/erpnext_ocr" --no-cache-dir \
    #    && bench build --app erpnext_ocr \
    #; \
    #sudo mkdir -p "${FRAPPE_WD}/sites"; \
    #sudo touch "${FRAPPE_WD}/sites/apps.txt"; \
    #sudo chown $FRAPPE_USER:$FRAPPE_USER "${FRAPPE_WD}/sites/apps.txt"; \
    #echo "frappe" > "${FRAPPE_WD}/sites/apps.txt"; \
    #echo "erpnext" >> "${FRAPPE_WD}/sites/apps.txt"; \
    #echo "erpnext_ocr" >> "${FRAPPE_WD}/sites/apps.txt"
